# Generated by Django 2.2.3 on 2019-08-12 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issue', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='issue_body',
            field=models.CharField(max_length=5000),
        ),
    ]
