# Generated by Django 2.2.3 on 2019-08-07 12:34

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sewer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gid', models.IntegerField()),
                ('type', models.CharField(blank=True, max_length=50, null=True)),
                ('pipe_type', models.CharField(blank=True, max_length=50, null=True)),
                ('p_diam_mm_field', models.BigIntegerField(blank=True, db_column='p_diam_mm_', null=True)),
                ('geom', django.contrib.gis.db.models.fields.MultiLineStringField(blank=True, null=True, srid=4326)),
            ],
            options={
                'db_table': 'sewer',
                'managed': False,
            },
        ),
    ]
